application: fileshare
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /delete/.*
  script: main.app
  login: admin

- url: /get/.*
  script: main.app
  
- url: .*
  script: main.app
  login: admin
